---
- hosts: localhost
  connection: local
  become: true

  tasks:
  - name: install htop
    package: 
      name: 
        - curl
        - fzf
        - gdb
        - gettext
        - git
        - htop
        - jq
        - meson
        - pandoc
        - ripgrep
        - shellcheck
        - steam
        - stow
        - sway
        - tmux
        - valgrind
        - vim
        - build-essential
        - ca-certificates
        - cmake
        - gnupg
        - gperf
        - lcov
        - ninja-build
        - pkg-config
        - scdoc
        - unzip
