---
- hosts: localhost
  connection: local
  become: true
  vars:
    wallpaper_path: /usr/share/backgrounds/ansible-wallpaper.png

  tasks:
  - name: install packages
    package: 
      name: 
        - build-essential
        - ca-certificates
        - cmake
        - curl
        - fzf
        - gdb
        - gettext
        - git
        - gnupg
        - gperf
        - htop
        - jq
        - lcov
        - meson
        - ninja-build
        - pandoc
        - pkg-config
        - ripgrep
        - scdoc
        - shellcheck
        - steam
        - stow
        - sway
        - tmux
        - tree
        - unzip
        - valgrind
        - vim

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: "{{ wallpaper_path }}"
      owner: root
      group: root

  - name: set wallpaper
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://{ wallpaper_path }}'"

  - name: set wallpaper position
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"
