---
- hosts: localhost
  connection: local
  become: true
  vars:
    wallpaper_path: /usr/share/backgrounds/ansible-wallpaper.png

  tasks:
  - name: install packages
    package: 
      name: 
        - build-essential
        - ca-certificates
        - cmake
        - curl
        - fzf
        - gdb
        - gettext
        - git
        - gnupg
        - gperf
        - htop
        - jq
        - lcov
        - meson
        - ninja-build
        - pandoc
        - pkg-config
        - python3-psutil
        - ripgrep
        - scdoc
        - shellcheck
        - steam
        - stow
        - sway
        - tmux
        - tree
        - unzip
        - valgrind
        - vim

  - name: copy wallpaper file
    copy:
      src: files/wallpaper.png
      dest: "{{ wallpaper_path }}"
      owner: root
      group: root

  - name: set wallpaper
    become_user: sgeisenh
    dconf:
      key: "/org/gnome/desktop/background/picture-uri"
      value: "'file://{{ wallpaper_path }}'"

  - name: set wallpaper position
    become_user: sgeisenh
    dconf:
      key: "/org/gnome/desktop/background/picture-options"
      value: "'zoom'"

  - name: add ansible user
    user:
      name: ansible-user
      system: yes

  - name: set up sudo for ansible user
    copy:
      src: files/sudoer_ansible_user
      dest: /etc/sudoers.d/sudoers_ansible_uer
      owner: root
      group: root
      mode: 0440

  - name: add ansible-pull cron job
    cron:
      name: ansible auto-provision
      user: ansible-user
      minute: "*/10"
      job: ansible-pull -o -U https://github.com/sgeisenh/provision
