---

- name: Install kitty
  become_user: sgeisenh
  vars:
    home_dir: "/home/sgeisenh"
    kitty_app_dir: "{{ home_dir }}/.local/kitty.app"
  block:
    - name: Create kitty directory
      ansible.builtin.file:
        path: "{{ kitty_app_dir }}"
        state: directory
        mode: "0755"

    - name: Install kitty
      become_user: sgeisenh
      ansible.builtin.unarchive:
        src: https://github.com/kovidgoyal/kitty/releases/download/v0.31.0/kitty-0.31.0-x86_64.txz
        dest: "{{ kitty_app_dir }}"
        remote_src: true

    - name: Link kitty binary
      ansible.builtin.file:
        src: "{{ kitty_app_dir }}/bin/kitty"
        dest: "{{ home_dir }}/.local/bin/kitty"
        state: link

    - name: Copy kitty icon
      ansible.builtin.copy:
        src: "{{ kitty_app_dir }}/share/applications/kitty.desktop"
        dest: "{{ home_dir }}/.local/share/applications"
        mode: "0664"

    - name: Change kitty icon file path
      ansible.builtin.lineinfile:
        path: "{{ home_dir }}/.local/share/applications/kitty.desktop"
        regexp: "^Icon=kitty$"
        line: "Icon={{ kitty_app_dir }}/share/icons/hicolor/256x256/apps/kitty.png"

    - name: Install kitty-terminfo
      ansible.builtin.apt:
        pkg: kitty-terminfo
      become: true
