---
- name: Install gpg so we can add keyrings
  ansible.builtin.apt:
    pkg: gnupg

- name: Add syncthing third-party repo
  block:
    - name: Add apt keyring for syncthing
      ansible.builtin.get_url:
        url: https://syncthing.net/release-key.gpg
        dest: /etc/apt/keyrings/syncthing-archive-keyring.gpg

    - name: Add apt source for syncthing
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/syncthing-archive-keyring.gpg] https://apt.syncthing.net/ syncthing stable"
        state: present

- name: Add nodesource third-party repo
  block:
    - name: Download NodeSource gpg key
      ansible.builtin.get_url:
        url: https://deb.nodesource.com/gpgkey/nodesource-repo.gpg.key
        dest: /tmp/nodesource-repo.gpg.key
        mode: '0644'
      changed_when: false

    - name: Add the GPG key to keyrings
      ansible.builtin.command:
        cmd: gpg --dearmor -o /etc/apt/keyrings/nodesource.gpg /tmp/nodesource-repo.gpg.key
        creates: /etc/apt/keyrings/nodesource.gpg

    - name: Add apt source for nodesource
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/nodesource.gpg] https://deb.nodesource.com/node_20.x nodistro main"
        state: present

- name: install packages
  ansible.builtin.apt:
    pkg:
      - curl
      - fd-find
      - fzf
      - git
      - gnome-tweaks
      - gnupg
      - htop
      - jq
      - meson
      - ninja-build
      - nodejs
      - pandoc
      - python3-psutil
      - ripgrep
      - ruby-full
      - shellcheck
      - steam
      - stow
      - sway
      - syncthing
      - tmux
      - tree
      - unzip
      - valgrind

- name: Install snaps
  when: ansible_distribution == "Ubuntu"
  community.general.snap:
    name:
      - chromium
      - bitwarden
    classic: true

- name: Install chromium
  when: ansible_distribution == "Debian"
  ansible.builtin.apt:
    pkg:
      - chromium

- name: Install bitwarden
  when: ansible_distribution == "Debian"
  block:
    - name: Download deb package
      ansible.builtin.get_url:
        url: https://vault.bitwarden.com/download/?app=desktop&platform=linux&variant=deb
        dest: /tmp/bitwarden.deb
    - name: Install deb package
      ansible.builtin.apt:
        deb: /tmp/bitwarden.deb
