---
- name: copy wallpaper file
  copy:
    src: files/wallpaper.png
    dest: "{{ wallpaper_path }}"
    owner: root
    group: root

- name: set wallpaper
  become_user: sgeisenh
  dconf:
    key: "/org/gnome/desktop/background/picture-uri"
    value: "'file://{{ wallpaper_path }}'"

- name: set wallpaper position
  become_user: sgeisenh
  dconf:
    key: "/org/gnome/desktop/background/picture-options"
    value: "'zoom'"
